# Generated by Django 6.0.7 on 2026-07-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("passwoord", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20)),
                ("mobile", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=50)),
            ],
        ),
    ]
