# Generated by Django 6.0.7 on 2026-07-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="passwoord",
            new_name="password",
        ),
    ]
