# Generated by Django 6.0.7 on 2026-07-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_rename_passwoord_customer_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "picture",
                    models.URLField(
                        default="https://elledecor.in/must-visit-restaurants-in-india-elle-decor-india-recommends/"
                    ),
                ),
                ("cuisine", models.CharField(max_length=200)),
                ("rating", models.FloatField()),
            ],
        ),
    ]
