# Generated by Django 6.0.7 on 2026-07-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="picture",
            field=models.URLField(
                default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxDZHfSwrp57B1QFsRkAY7RPvW1CdYiV9JGsumUEcC8w&s=10"
            ),
        ),
    ]
