# Generated by Django 6.0.7 on 2026-08-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0006_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="item",
        ),
        migrations.AddField(
            model_name="cart",
            name="items",
            field=models.ManyToManyField(related_name="carts", to="delivery.item"),
        ),
    ]
