# Generated by Django 6.0.7 on 2026-08-06 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0007_remove_cart_item_cart_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="carts", to="delivery.item"
            ),
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="delivery.cart",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="delivery.item"
                    ),
                ),
            ],
        ),
    ]
